# Generated by Django 2.2 on 2021-11-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_csvdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='Mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='Start_date',
            field=models.CharField(max_length=15),
        ),
    ]
