# Generated by Django 2.2 on 2021-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0003_auto_20211106_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdata',
            name='Mobile',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='Salary',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='csvdata',
            name='Start_date',
            field=models.DateField(),
        ),
    ]
