# Generated by Django 2.2 on 2021-11-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsxdata',
            name='Start_date',
            field=models.CharField(max_length=20),
        ),
    ]
