# Generated by Django 2.2 on 2021-11-07 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0002_auto_20211107_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xlsxdata',
            name='Start_date',
            field=models.DateField(),
        ),
    ]
