# Generated by Django 2.2 on 2021-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excel', '0004_auto_20211106_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xlsx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='xlsx')),
                ('activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='CsvData',
            new_name='XlsxData',
        ),
        migrations.DeleteModel(
            name='Csv',
        ),
    ]
